### ISSUE TITLE
Opportunity at our startup

### ISSUE THREAD

**Issue by ghost** [AbeerRao/blackberry-reborn#1]
I hope this message finds you well.

**Comment by AbeerRao** [comment]
Hi Rahul,

I dont use Telegram. Lets continue on email. I sent you one regarding the same

**Comment by ghost** [comment]
alright

**Comment by saikumarpb** [comment]
@AbeerRao This guy (Rahul) is stealing the ssh keys and system information. If you have already connected with him he might have asked you to clone a repo and npm start it. this is executing a [script](https://github.com/rahul-shankar79/backend/blob/main/bin/cache/install.sh). Please be careful. If you are already a victim delete all your ssh keys.

**Comment by AbeerRao** [comment]
Hi Sai.

No I haven't yet shared anything with him. But thank you so much from bringing this to attention. I might have fallen prey if not for you. Thank you so much, really appreciate it.
